#!/usr/bin/env python3
"""
Plot AODV vs AOMDV performance from a single CSV across multiple error rates.

Expected CSV columns include:
- Protocol
- ErrorRate
- PDR_pct
- Throughput_kbps
- AvgDelay
- PacketLossRate_pct

Usage:
    python3 scratch/plot-aodv-aomdv-comparison.py \
        --csv aodv-aomdv-results.csv \
        --outdir comparison-graphs-aodv-aomdv
"""

import argparse
import os
import sys

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd


METRICS = {
    "PDR_pct": ("Packet Delivery Ratio", "%"),
    "Throughput_kbps": ("Avg Throughput", "kbps"),
    "AvgDelay": ("Avg Delay", "ms"),
    "PacketLossRate_pct": ("Packet Loss Rate", "%"),
}

ERROR_COLORS = {
    0.0: "#6baed6",
    0.1: "#fd8d3c",
    0.2: "#74c476",
}


def load(path: str) -> pd.DataFrame:
    if not os.path.exists(path):
        print(f"ERROR: file not found: {path}")
        sys.exit(1)

    df = pd.read_csv(path)

    if "AvgDelay" not in df.columns and "DelayWithLossPenalty_ms" in df.columns:
        df = df.rename(columns={"DelayWithLossPenalty_ms": "AvgDelay"})

    required = {"Protocol", "ErrorRate"} | set(METRICS.keys())
    missing = sorted(required - set(df.columns))
    if missing:
        print(f"ERROR: missing required columns: {missing}")
        sys.exit(1)

    return df


def per_protocol_error_mean(df: pd.DataFrame) -> pd.DataFrame:
    return df.groupby(["Protocol", "ErrorRate"]).mean(numeric_only=True).reset_index()


def plot(df: pd.DataFrame, outdir: str):
    grouped = per_protocol_error_mean(df)

    protocols = sorted(grouped["Protocol"].unique())
    error_rates = sorted(grouped["ErrorRate"].unique())

    if not protocols or not error_rates:
        print("ERROR: No data to plot.")
        sys.exit(1)

    x = np.arange(len(protocols))
    n_errors = len(error_rates)
    bar_w = 0.8 / n_errors

    fig, axes = plt.subplots(1, 4, figsize=(20, 6))
    fig.suptitle("AODV vs AOMDV Across Error Rates", fontsize=15, fontweight="bold", y=1.01)

    for ax, (metric, (title, unit)) in zip(axes, METRICS.items()):
        for i, er in enumerate(error_rates):
            sub = grouped[grouped["ErrorRate"] == er].set_index("Protocol")
            vals = [sub.loc[p, metric] if p in sub.index else 0 for p in protocols]
            xpos = x - 0.4 + (i + 0.5) * bar_w
            color = ERROR_COLORS.get(er, None)
            bars = ax.bar(
                xpos,
                vals,
                bar_w,
                label=f"{int(er * 100)}% Error",
                color=color,
                edgecolor="black",
                linewidth=0.7,
            )

            for bar, val in zip(bars, vals):
                if val > 0:
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + ax.get_ylim()[1] * 0.01,
                        f"{val:.1f}",
                        ha="center",
                        va="bottom",
                        fontsize=8,
                    )

        ax.set_title(f"{title}\n({unit})", fontsize=11, fontweight="bold")
        ax.set_xticks(x)
        ax.set_xticklabels(protocols, fontsize=10)
        ax.set_ylabel(unit, fontsize=9)
        ax.grid(axis="y", alpha=0.3, linestyle="--")
        ax.set_ylim(bottom=0)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

    legend_handles = [
        mpatches.Patch(
            facecolor=ERROR_COLORS.get(er, "gray"),
            edgecolor="black",
            label=f"{int(er * 100)}% Error",
        )
        for er in error_rates
    ]
    fig.legend(
        handles=legend_handles,
        loc="lower center",
        ncol=max(1, len(error_rates)),
        fontsize=12,
        frameon=True,
        bbox_to_anchor=(0.5, -0.06),
    )

    os.makedirs(outdir, exist_ok=True)
    outpath = os.path.join(outdir, "aodv_aomdv_comparison.png")
    plt.tight_layout()
    plt.savefig(outpath, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved: {outpath}")


def main():
    parser = argparse.ArgumentParser(
        description="Plot AODV vs AOMDV MANET metrics across error rates from one CSV."
    )
    parser.add_argument("--csv", required=True, help="Input CSV generated by 08-extended-sim.cc")
    parser.add_argument("--outdir", default="comparison-graphs-aodv-aomdv", help="Output directory")
    args = parser.parse_args()

    df = load(args.csv)
    plot(df, args.outdir)


if __name__ == "__main__":
    main()
